FROM openjdk:11.0

ADD target/employeeSpringBootApp-0.0.1-SNAPSHOT.jar app.jar

RUN sh -c 'echo spring.datasource.url=jdbc:mysql://mysql:3306/demo?serverTimezone=UTC&SSL=false > application.properties'
RUN sh -c 'echo spring.datasource.username=root    >> application.properties'
RUN sh -c 'echo spring.datasource.password=C0nygre-C0nygre >> application.properties'

EXPOSE 8888

ENTRYPOINT ["java","-jar","/app.jar"]
